---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

script:
  - yarn lint:js
  - yarn test
  - npm run build -- -prod # build app and prepare dist folder

# deploy master branch to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "74f959b592dedd476989f7fd2df92986de60606c"
  keep-history: true
  on:
    branch: master
  local-dir: dist
  verbose: true


